language: csharp
solution: SimCivil.sln
mono: none
dotnet: 2.1.3
dist: trusty
script:
   - dotnet build SimCivil
   - dotnet test SimCivil.Test --filter "Category!=Performance" 
notifications:
    slack: tpdt:fmYoCUlHFzbEE9YxZctMJjJl
